# Operasi Aritmatika

In [1]:
import numpy as np

# List Python

In [2]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

In [3]:
a

[1, 2, 3, 4, 5]

In [4]:
b

[6, 7, 8, 9, 10]

In [5]:
hasil = a + b
hasil

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Numpy Array

In [6]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [7]:
a1

array([1, 2, 3, 4, 5])

In [8]:
a2

array([ 6,  7,  8,  9, 10])

In [9]:
hasil = a1 + a2
hasil

array([ 7,  9, 11, 13, 15])

In [10]:
hasil = a1 - a2
hasil

array([-5, -5, -5, -5, -5])

In [11]:
hasil = a1 * a2
hasil

array([ 6, 14, 24, 36, 50])

In [12]:
hasil = a1 / a2
hasil

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [13]:
hasil = a1**2
hasil

array([ 1,  4,  9, 16, 25])

# Multi Dimensi Array Numpy

In [14]:
a3 = np.array([[1,2,3],[4,5,6]])
a4 = np.array([[[7,8,9],[-1,-2,-3]]])

In [15]:
hasil = a3 + a4
hasil

array([[[ 8, 10, 12],
        [ 3,  3,  3]]])

In [16]:
hasil = a3 - a4
hasil

array([[[-6, -6, -6],
        [ 5,  7,  9]]])

In [18]:
hasil = a3 * a4
hasil

array([[[  7,  16,  27],
        [ -4, -10, -18]]])