# Solusi Persamaan Linear

# Import Module

In [1]:
import numpy as np

In [3]:
A = np.array([[2,3],[1,2]])
Y = np.array([23,14])

In [4]:
A

array([[2, 3],
       [1, 2]])

In [5]:
Y

array([23, 14])

In [6]:
A_inv = np.linalg.inv(A)

# Menyelesaikan Persamaan Linear

In [8]:
X1 = np.dot(A_inv,Y)
X1

array([4., 5.])

# Cara Lain

In [9]:
X2 = np.linalg.solve(A,Y)
X2

array([4., 5.])