# Sorting NumPy Array

# Import Module

In [42]:
import numpy as np

In [43]:
a = np.floor(np.random.randn(1,6)*10)
a

array([[ -8.,   4., -23.,  10., -14.,  18.]])

In [44]:
print("Nilai Max Dari a = {}".format(a.max()))

Nilai Max Dari a = 18.0


In [45]:
print("Posisi Nilai Max Dari a = {}".format(a.argmax()))

Posisi Nilai Max Dari a = 5


In [46]:
print(f"Nilai Min Dari a = {a.min()}")

Nilai Min Dari a = -23.0


In [49]:
print(f"Posisi Nilai Min Dari a = {a.argmin()}")

Posisi Nilai Min Dari a = 2


# Mengurutkan Nilai

In [68]:
b = np.floor(np.random.rand(2,2)*10)
b

array([[3., 1.],
       [7., 4.]])

In [69]:
np.sort(b)

array([[1., 3.],
       [4., 7.]])

In [70]:
np.argsort(b)

array([[1, 0],
       [1, 0]], dtype=int64)